#pragma once
//int Score;
void init();
void DisplayGame();
void drawShape(int,int,struct node* head);
struct node* ClipLeft(struct node* points, float left);
struct node* ClipRight(struct node* points, float right);
struct node* ClipTop(struct node* points, float top);
struct node* ClipBottom(struct node* points, float top);
struct node* Translate(struct node* points, float left, float bottom);
struct node* Clip(struct node* points, float left, float right, float top, float bottom);
struct node* GetCopy(struct node* points);
//void keyFunc(unsigned char k, int x, int y);
//void keySpe(int k, int x, int y);
struct node* deleteFirst(node* head);
struct node* insertFirst(node* head, float x1, float y1);
//void Idle();
//void Circle(float y);
void drawPatch();
void drawShape(int Scane, int Count, struct node* head);
struct node* drawElipse(struct node* head, float xc, float yc, float x_len, float y_len);
void initScane1();
void init_Pizzle();
void displayMenu();
void init_Menu();
void init_Story1();
void displayStory1();
void init_Story2();
void displayStory2();
void displayScore1();
void init_Score1();
void DisplayMaze();
void init_Maze();
void Load_HS();
void init_HS();
void displayHS();
void init_Story3();
void displayStory3();
void init_Story4();
void displayStory4();